### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by alajangi** [danieltardon/kafka-hue#17]
HI danieltardon,
When I run 
# ../tools/app_reg/app_reg.py --install kafka --relative-paths 
=== Installing app at kafka
=== kafka v.1.0 is already installed
=== Saved registry at /opt/cloudera/parcels/CDH-5.2.1-1.cdh5.2.1.p0.12/lib/hue/app.reg
=== Saved /opt/cloudera/parcels/CDH-5.2.1-1.cdh5.2.1.p0.12/lib/hue/build/env/lib/python2.6/site-packages/hue.pth
Running '/opt/cloudera/parcels/CDH-5.2.1-1.cdh5.2.1.p0.12/lib/hue/build/env/bin/hue syncdb --noinput' with None
/opt/cloudera/parcels/CDH-5.2.1-1.cdh5.2.1.p0.12/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/conf/__init__.py:110: DeprecationWarning: The SECRET_KEY setting must not be empty.
  warnings.warn("The SECRET_KEY setting must not be empty.", DeprecationWarning)
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.auth
 > django_openid_auth
 > django.contrib.contenttypes
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.admin
 > django_extensions
 > south
 > indexer
 > kafka

Not synced (use migrations):
 - desktop
(use ./manage.py migrate to migrate these)
Running '/opt/cloudera/parcels/CDH-5.2.1-1.cdh5.2.1.p0.12/lib/hue/build/env/bin/hue migrate --merge' with None
/opt/cloudera/parcels/CDH-5.2.1-1.cdh5.2.1.p0.12/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/conf/__init__.py:110: DeprecationWarning: The SECRET_KEY setting must not be empty.
  warnings.warn("The SECRET_KEY setting must not be empty.", DeprecationWarning)
Running migrations for desktop:
- Nothing to migrate.
 - Loading initial data for desktop.
Installed 0 object(s) from 0 fixture(s)
what could be the problem, please help me.

Thanks.

**Comment by danieltardon** [comment]
alajangi

Did you manage to resolve your problem?

**Comment by alajangi** [comment]
Yes Daniel.

On Wed, Jan 7, 2015 at 1:43 AM, Daniel Tardón <notifications@github.com>
wrote:

> alajangi
>
> Did you manage to resolve your problem?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/danieltardon/kafka-hue/issues/17#issuecomment-68999103>
> .
>



-- 
Thanks,
Kishore.

**Comment by danieltardon** [comment]
Great! 

It would be nice if you share with us what was the real problem and how you fix it to close the issue. 

Thanks

**Comment by danieltardon** [comment]
Unknown issue.
